### ISSUE TITLE
Attach a file to a product

### ISSUE THREAD

**Issue by acechase** [fetchapp/fetchapp-api-ruby#6]
Is it possible to use the /items resource to upload a file and associate that file with an item?

I see in the documentation how to POST to create an item, but it looks like all that POST allows for is the specification of metadata.  What resource path should I be interacting with to create a new file, would that be a POST to the /uploads resource? If so, how should I pass the file data?

Thanks!

**Comment by mikelarkin** [comment]
Unfortunately, not yet :-(

At this time it's not possible to upload files via the API, though we're definitely thinking about adding it.  Right now we use a flash uploader that posts directly to our file server (and not through our web server), but if we allowed uploads via the API, we'd have to proxy the upload to our file server through our web server which would block the process....which is what we're trying to avoid so that the site stays snappy.

For files of a few MB this wouldn't be a problem, but we have some clients that have files in the 500 MB+ range, so this could end up taking several minutes / hour(s) depending on their speed.

**Comment by mikelarkin** [comment]
Wanted to post an update to this to say that while uploading the file data itself still isn't possible, it is now possible to programmatically assign existing files to products via the API.
